spring.application.name=teams-scaler

server.port=8082

spring.kafka.consumer.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVER}
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.consumer.group-id=keda-inbound-trigger-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.producer.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVER}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer


spring.kafka.listener.ack-mode=manual_immediate





spark.home=${SPARK_HOME}
spark.deploy.mode=${SPARK_DEPLOY_MODE}
spark.master=${SPARK_MASTER}
spark.image=${SPARK_IMAGE}
spark.s3.url=${SPARK_S3_URL}
spark.catalog.url=${SPARK_CATALOG_URL}